(() => {
  "use strict";
  const API = "http://127.0.0.1:5040";
  const AUTH = { usuario:"acesso", senhaHash:"1j78k6ardjv", storageKey:"portal504_auth_v1" };
  const portalInfo = {
    tpo:{name:"TPO", icon:"TPO", accent:"#4aa3ff", desc:"Athena → Packaging → relatório do mês → Portal TPO", manual:"../Lobby/Portal Qualidade/Portal TPO/index.html"},
    up:{name:"UP", icon:"UP", accent:"#7b7cf6", desc:"Athena → Packaging + Linha 504 → Portal UP", manual:"../Lobby/Portal Qualidade/Portal UP/index.html"},
    seguranca:{name:"Segurança", icon:"TRI", accent:"#27d3c4", desc:"Guardian → 4 relatórios → Portal Segurança", manual:"../Lobby/Portal Segurança/index_seguranca_504.html"},
    manutencao:{name:"Manutenção", icon:"OSE", accent:"#ff8d42", desc:"SAP/IW38 → ordens_status.htm → Git/GitHub", manual:"../Lobby/Portal manutenção/index_programacao_operacional.html"}
  };
  function hashCredential(value){let h1=0xdeadbeef^value.length,h2=0x41c6ce57^value.length;for(let i=0,ch;i<value.length;i++){ch=value.charCodeAt(i);h1=Math.imul(h1^ch,2654435761);h2=Math.imul(h2^ch,1597334677)}h1=Math.imul(h1^(h1>>>16),2246822507)^Math.imul(h2^(h2>>>13),3266489909);h2=Math.imul(h2^(h2>>>16),2246822507)^Math.imul(h1^(h1>>>13),3266489909);return(4294967296*(2097151&h2)+(h1>>>0)).toString(36)}
  const tokenEsperado=hashCredential(`portal504|${AUTH.usuario}|${AUTH.senhaHash}|autorizado`);
  function sessaoValida(){try{if(window.name.startsWith("PORTAL504_AUTH:")){const x=JSON.parse(decodeURIComponent(window.name.slice("PORTAL504_AUTH:".length)));if(x&&x.token===tokenEsperado&&Date.now()<x.expiraEm)return true}const raw=localStorage.getItem(AUTH.storageKey);if(!raw)return false;const s=JSON.parse(raw);return s&&s.token===tokenEsperado&&Number.isFinite(s.expiraEm)&&Date.now()<s.expiraEm}catch(_){return false}}
  if(!sessaoValida()){window.location.replace(`index.html?retorno=${encodeURIComponent(window.location.href)}`);return}
  document.getElementById("updatesPage").hidden=false;document.body.classList.remove("updates-auth-pending");

  const fmtDate=v=>{if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"})};
  const fmtDuration=ms=>{if(!Number.isFinite(ms))return "—";const s=Math.round(ms/1000);if(s<60)return `${s}s`;return `${Math.floor(s/60)}min ${s%60}s`};
  let latest=null;
  async function api(path,opts={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),2500);try{const r=await fetch(API+path,{...opts,signal:c.signal,headers:{"Content-Type":"application/json",...(opts.headers||{})}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
  function renderOffline(){latest=null;const p=document.getElementById("agentPill");p.className="agent-pill offline";p.querySelector("span").textContent="Central local não iniciada";document.getElementById("environmentText").textContent="Abra INICIAR_PORTAL_504.bat para habilitar as automações neste VD.";document.getElementById("availableCount").textContent="0";document.getElementById("runningCount").textContent="0";renderCards({automations:{}});}
  function renderCards(data){const host=document.getElementById("automationGrid");host.innerHTML=Object.entries(portalInfo).map(([id,info])=>{const a=data.automations?.[id]||{};const run=data.running?.id===id;const available=!!a.available;const last=data.history?.find(x=>x.id===id);const status=run?"running":last?.result==="success"?"success":last?.result==="error"?"error":available?"ready":"unavailable";const label={running:"Executando",success:"Último: sucesso",error:"Último: erro",ready:"Disponível",unavailable:"Indisponível"}[status];return `<article class="automation-card" style="--accent:${info.accent}"><div class="card-top"><div class="portal-icon">${info.icon}</div><span class="status-badge ${status}">${label}</span></div><h3>${info.name}</h3><p class="desc">${info.desc}</p><div class="meta"><div class="meta-row"><span>Última execução</span><b>${last?fmtDate(last.endedAt||last.startedAt):"Sem histórico"}</b></div><div class="meta-row"><span>Arquivo/base</span><b>${a.fileUpdatedAt?fmtDate(a.fileUpdatedAt):"—"}</b></div><div class="meta-row"><span>Ambiente</span><b>${available?"Pronto neste VD":(a.reason||"Não localizado")}</b></div></div><button class="run-btn" data-run="${id}" ${(!available||data.running)?"disabled":""}>${run?"ATUALIZANDO...":"ATUALIZAR AGORA"}</button></article>`}).join("");host.querySelectorAll("[data-run]").forEach(b=>b.onclick=()=>runAutomation(b.dataset.run));}
  function renderHistory(rows=[]){const body=document.getElementById("historyBody");body.innerHTML=rows.length?rows.slice(0,20).map(x=>`<tr><td><b>${portalInfo[x.id]?.name||x.id}</b></td><td>${fmtDate(x.startedAt)}</td><td>${fmtDate(x.endedAt)}</td><td>${fmtDuration(x.durationMs)}</td><td class="${x.result==='success'?'result-ok':'result-error'}">${x.result==='success'?'SUCESSO':'ERRO'}</td></tr>`).join(""):'<tr><td colspan="5">Nenhuma execução registrada por esta Central.</td></tr>';}
  function renderOnline(data){latest=data;const p=document.getElementById("agentPill");p.className="agent-pill online";p.querySelector("span").textContent="Automação disponível neste VD";const av=Object.values(data.automations||{}).filter(x=>x.available).length;document.getElementById("availableCount").textContent=`${av}/4`;document.getElementById("runningCount").textContent=data.running?"1":"0";const success=(data.history||[]).find(x=>x.result==="success");document.getElementById("lastSuccess").textContent=success?portalInfo[success.id]?.name||success.id:"—";document.getElementById("lastSuccessDetail").textContent=success?fmtDate(success.endedAt):"sem histórico local";const missing=Object.entries(data.automations||{}).filter(([,v])=>!v.available).map(([k])=>portalInfo[k]?.name||k);document.getElementById("environmentText").textContent=missing.length?`Node OK. Automação não localizada: ${missing.join(", ")}.`:`Node OK • 4 automações localizadas • uma execução por vez.`;renderCards(data);renderHistory(data.history||[]);}
  async function refresh(){try{renderOnline(await api("/status"))}catch(_){renderOffline()}}
  async function runAutomation(id){const info=portalInfo[id];if(!info)return;if(!confirm(`Executar atualização automática de ${info.name}?\n\nO Portal de Indicadores pode permanecer aberto.`))return;try{await api(`/run/${id}`,{method:"POST",body:"{}"});await refresh()}catch(e){alert(`Não foi possível iniciar ${info.name}.\n\nVerifique se a Central local está iniciada e se nenhuma outra automação está rodando.`);await refresh()}}
  document.getElementById("refreshStatus").onclick=refresh;refresh();setInterval(refresh,3500);
})();